import { MenuInterFace } from './menuinterface';

export const menu: MenuInterFace[] = [		
	{	id: 1, 
		dishname: "Voluptate cillum fugiat.", 
		dishdescription: "Cheese, tomato, mushrooms, onions.", 
		dishweight: 350, 
		dishprice: 50	},		
	{	id: 2, 
		dishname: "Arcu pede enim justo.", 
		dishdescription: "Tuna, Sweetcorn, Cheese.", 
		dishweight: 400, 
		dishprice: 45	},
	{	id: 3, 
		dishname: "Cras dapibussemer nisi.", 
		dishdescription: "Pineapple, Minced Beef, Cheese.", 
		dishweight: 370, 
		dishprice: 55	},
	{	id: 4, 
		dishname: "Donec sodales magna.", 
		dishdescription: "Tuna, Sweetcorn, Cheese.", 
		dishweight: 420, 
		dishprice: 47	},
	{	id: 5, 
		dishname: "Quam semper libero.", 
		dishdescription: "Cheese, tomato, mushrooms, onions.", 
		dishweight: 370, 
		dishprice: 55	},
	{	id: 6, 
		dishname: "Saugue velit cursus.", 
		dishdescription: "Pineapple, Minced Beef, Cheese.", 
		dishweight: 320, 
		dishprice: 45	},
	{	id: 7, 
		dishname: "Nam eget dui Etiam.", 
		dishdescription: "Chicken, mozzarella cheese, onions.", 
		dishweight: 370, 
		dishprice: 42	}
]